SET C51INC=d:\Keil c51_fu68xx\C51\Inc;d:\Keil c51_fu68xx\C51\Inc\FTC6801
SET C51LIB=d:\Keil c51_fu68xx\C51\Lib
SET CPU_TYPE=FU68XX
SET CPU_VENDOR=Fortior Tech
SET UV2_TARGET=Fu68xx_MC
SET CPU_XTAL=0x016E3600
"d:\Keil c51_fu68xx\C51\BIN\C51.EXE" @.\obj\FU68XX~1.__I
"d:\Keil c51_fu68xx\C51\BIN\C51.EXE" @.\obj\FU68XX~2.__I
"d:\Keil c51_fu68xx\C51\BIN\C51.EXE" @.\obj\FU68XX~3.__I
"d:\Keil c51_fu68xx\C51\BIN\C51.EXE" @.\obj\FU68XX~4.__I
"d:\Keil c51_fu68xx\C51\BIN\C51.EXE" @.\obj\FU42A8~1.__I
